//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAGY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public long ID { get; set; }
        public long MessageID { get; set; }
        public long FromUserID { get; set; }
        public long ToUserID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
    }
}
