//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAGY.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TagyEntities : DbContext
    {
        public TagyEntities()
            : base("name=TagyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PreferedLocation> PreferedLocations { get; set; }
        public virtual DbSet<Role_User> Role_User { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<TAG> TAGS { get; set; }
        public virtual DbSet<Tags_Messages> Tags_Messages { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
